#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


START = "# >>> opencode closed-network index ignore >>>"
END = "# <<< opencode closed-network index ignore <<<"

SCAN_PATTERNS = [
    ".opencode/",
    ".opencode/node_modules/",
    ".venv/",
    "venv/",
    "env/",
    "ENV/",
    "__pycache__/",
    "*.py[cod]",
    ".DS_Store",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".ipynb_checkpoints/",
    "node_modules/",
    "dist/",
    "build/",
    ".cache/",
    "*.whl",
    "*.tar.gz",
    "*.zip",
    "mlartifacts/",
    "mlflow.db",
    "ai_studio/tracking/",
        "ai_studio/metrics/",
    "ai_studio/code/",
    "ai_studio/artifacts/",
    "artifacts/",
    "runs/",
    "wandb/",
    "lightning_logs/",
    "checkpoints/",
    "dataset/",
    "datasets/",
    "data/raw/",
    "data/processed/",
    "model/",
    "models/",
    "saved_model/",
    "*.log",
    "*.csv",
    "*.tsv",
    "*.parquet",
    "*.npy",
    "*.npz",
    "*.pt",
    "*.pth",
    "*.onnx",
    "*.h5",
    "*.keras",
    "*.pkl",
    "*.joblib",
    "*.safetensors",
    "*.bst",
    "*.ubj",
]

GIT_PATTERNS = [
    pattern
    for pattern in SCAN_PATTERNS
    if pattern not in {".opencode/", ".opencode/node_modules/"}
] + [
    "!.opencode/samples/pytorch_sample/saved_model/",
    "!.opencode/samples/pytorch_sample/saved_model/.gitkeep",
]

TARGET_FILES = {
    ".ignore": SCAN_PATTERNS,
    ".rgignore": SCAN_PATTERNS,
    ".gitignore": GIT_PATTERNS,
}


def resolve_workspace_project(raw_project: str) -> Path:
    raw = raw_project.strip()
    if raw in {"<workspace-root>", "<current-project-folder>", "<model-project-folder>"}:
        raw = "."
    elif "<" in raw or ">" in raw:
        raise ValueError("replace placeholder project path before running, for example: --project .")

    project = Path(raw).expanduser().resolve()
    parts = project.parts
    if ".opencode" in parts:
        opencode_index = parts.index(".opencode")
        if opencode_index > 0:
            return Path(*parts[:opencode_index]).resolve()
    return project


def managed_block(patterns: list[str]) -> str:
    lines = [
        START,
        "# Generated by apply_index_ignore.py",
        "# Speeds up OpenCode/file-tree scans in closed-network ML workspaces.",
        *patterns,
        END,
        "",
    ]
    return "\n".join(lines)


def replace_or_append(text: str, block: str) -> tuple[str, str]:
    if START in text and END in text:
        before, rest = text.split(START, 1)
        _, after = rest.split(END, 1)
        prefix = before.rstrip()
        separator = "\n\n" if prefix else ""
        return prefix + separator + block + after.lstrip("\n"), "updated"
    if text.strip():
        return text.rstrip() + "\n\n" + block, "appended"
    return block, "created"


def apply_file(path: Path, block: str, dry_run: bool) -> str:
    existing = path.read_text(encoding="utf-8", errors="ignore") if path.exists() else ""
    next_text, status = replace_or_append(existing, block)
    if next_text != existing and not dry_run:
        path.write_text(next_text, encoding="utf-8")
    if next_text == existing:
        return "unchanged"
    return status if not dry_run else f"would_{status}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply closed-network index ignore rules to a workspace.")
    parser.add_argument("--project", default=".", help="workspace root to update")
    parser.add_argument("--dry-run", action="store_true", help="show changes without writing files")
    args = parser.parse_args()

    project = resolve_workspace_project(args.project)
    if not project.exists():
        raise SystemExit(f"project not found: {project}")

    print("Project: .")
    for name, patterns in TARGET_FILES.items():
        path = project / name
        block = managed_block(patterns)
        status = apply_file(path, block, args.dry_run)
        print(f"{name}: {status}")

    print("\nIndex ignore targets:")
    for pattern in SCAN_PATTERNS:
        print(f"- {pattern}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
